### PR TITLE
Cimpl6 comments

### PR DESCRIPTION
**Pull request by AmartC**

### CODE REVIEW

**Comment by kjmahalingam** [comment]
This looks reasonable to me.

Assuming that @markkramerus and/or @cmoesel can follow the instructions in the README and get the code to run as expected, I think this is good to go.

**Comment by cmoesel** [comment]
@markkramerus -- I think you've run this already, right?  Are you happy with the resulting output?

**Comment by cmoesel** [comment]
@AmartC -- @markkramerus says he hasn't reviewed any of the outputs from your comments tool.  Can you please show him how to run it or run it yourself on the dev branch and send him the results so he can review?

**Comment by cmoesel** [comment]
Closing in favor of the new CIMPL6 PR that includes the comments reintegration.

**Pull request closed without merging**
